---
kind: pipeline
type: docker
name: test & deploy

steps:
  - name: test
    image: node:lts-alpine
    commands:
      - yarn
      - yarn build
  - name: update server files
    image: alpine/git
    when:
      branch: master
    volumes:
      - name: server
        path: /server
    commands:
      - cd /server/_repos/telescope
      - git pull --rebase
  - name: deploy to server
    image: docker/compose
    when:
      branch: master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - cd /server
      - ./start.sh telescope --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server
---
kind: signature
hmac: 51fc2d0fec767b1b1a82b0cc603bee583953bb439dccd88023d4cc1bbd166c84
