# !! Attention !!
version: '3.5'

services:
  telescope:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - DISCORD_API_KEY

  # telescope_prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: prod
  #   restart: unless-stopped
  #   environment:
  #     - DISCORD_API_KEY
